name: Build

on:
  push:
    branches: [ "master", "workflow" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Check docker version
        run: |
          docker build --no-cache -t 5bcf4107 .
      - name: Start container
        run: |
          docker run --rm 5bcf4107
          